import numpy as np
import torch
from rdkit import Chem

NUM2ELEMENT = {num: Chem.GetPeriodicTable().GetElementSymbol(num) 
               for num in range(100)}
ELEMENT2NUM = {v: k for k, v in NUM2ELEMENT.items()}


def get_xyz_str(atom_num: torch.Tensor, geometry: torch.Tensor) -> str:
    atom_num = atom_num.cpu().numpy()
    geometry = geometry.cpu().numpy()
    
    content = ''
    content += f'{len(atom_num)}\n'
    title = '\n'
    content += title

    atom_map = np.vectorize(lambda num: NUM2ELEMENT[num].ljust(2))
    elements  = atom_map(atom_num.tolist())

    # Extract geometry and format with 4 decimal places
    geom_lines = np.core.defchararray.add(
        np.char.rjust(np.char.mod('%.4f', geometry[:, 0]), 12),
        np.core.defchararray.add(
            np.char.rjust(np.char.mod('%.4f', geometry[:, 1]), 12),
            np.char.rjust(np.char.mod('%.4f', geometry[:, 2]), 12)
        )
    )

    # Combine element symbols with the coordinates
    atom_lines = np.core.defchararray.add(
        np.char.add(np.char.add(' ', elements), '   '), geom_lines)
    content += '\n'.join(atom_lines) + '\n'

    return content


def get_sdf_str(
    atom_num: torch.Tensor, 
    geometry: torch.Tensor,
    edge_index: torch.Tensor,
    bond_order: torch.Tensor
) -> str:
    atom_num = atom_num.cpu().numpy()
    geometry = geometry.cpu().numpy()
    edge_index = edge_index.cpu().numpy()
    bond_order = bond_order.squeeze().cpu().numpy()
    # edge_index is undirected, so we need to convert it to directed
    mask = edge_index[0] < edge_index[1]
    edge_index = edge_index[:, mask]
    bond_order = bond_order[mask]
    
    src, dst = edge_index
    mol_len = len(atom_num)

    # Header
    content = ''
    content += '\n'
    content += '   Generated by shell\n'
    content += '\n'
    content += f'{mol_len:>3}{len(src):>3}  0  0  1  0  0  0  0  0999 V2000\n'

    # Atom block
    atom_map = np.vectorize(lambda num: NUM2ELEMENT[num].ljust(2))
    elem = atom_map(atom_num)
    geom_lines = np.core.defchararray.add(
        np.char.rjust(np.char.mod('%.4f', geometry[:, 0]), 10),
        np.core.defchararray.add(
            np.char.rjust(np.char.mod('%.4f', geometry[:, 1]), 10),
            np.char.rjust(np.char.mod('%.4f', geometry[:, 2]), 10)
        )
    )
    atom_lines = np.core.defchararray.add(geom_lines, np.char.add(' ', elem))
    trailing = '  0  0  0  0  0  0  0  0  0  0  0  0\n'
    content += ''.join(np.core.defchararray.add(atom_lines, trailing))

    # Bond block
    for i, j, o in zip(src, dst, bond_order):
        if abs(o - int(o)) < 1e-3:
            o = int(o)
        elif o == 1.5:  # aromatic
            o = 4
        else:
            raise ValueError(f'Invalid bond order {o} for {i} - {j} bond.')
        content += f'{i + 1:>3}{j + 1:>3}{o:>3}  0\n'

    # Footer
    content += 'M  END\n'
    content += '$$$$\n'

    return content